name: Build and Release C++ Project GameEngine

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up CMake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build with CMake
      run: cmake --build build

    - name: Create Release Directory
      run: mkdir release

    - name: Move Library to Release
      run: move build\lib\libUnitiGameEngine.lib release\

    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: release/* # Specify the files you want to include in the release
      env:
        GITHUB_TOKEN: "token_release"
