name: Build and Release C++ Project GameEngine

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up CMake
      run: cmake -S . -B build

    - name: Build with CMake
      run: cmake --build build

    - name: Create Release Directory
      run: mkdir release

    - name: Move Library to Release
      if: ${{ runner.os == 'Linux' }}
      run: mv build/lib/libUnitiGameEngine.a release/

    - name: Move Library to Release (Windows)
      if: ${{ runner.os == 'Windows' }}
      run: move build\lib\libUnitiGameEngine.lib release\

    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: release/* # Spécifiez les fichiers que vous souhaitez ajouter à la version
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Assurez-vous que vous avez le token GITHUB_TOKEN dans vos secrets de repository

    - name: Display Release URL
      run: echo "Release URL: ${{ steps.create_release.outputs.html_url }}"
