name: Build and Release C++ Project GameEngine

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up CMake
      run: cmake -S . -B build

    - name: Build with CMake
      run: cmake --build build

    - name: Create Release Directory
      run: mkdir release

    - name: Move Library to Release
      if: ${{ runner.os == 'Linux' }}
      run: mv build/libYourLibrary.a release/

    - name: Move Library to Release (Windows)
      if: ${{ runner.os == 'Windows' }}
      run: move build\YourLibrary.lib release\

    - name: Upload Release Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: release
        path: release/
