name: Build and Release C++ Project GameEngine

on:
  push:
    branches:
      - main
    tags:
      - '*' # Déclencher l'action pour toutes les balises


jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up CMake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build with CMake
      run: cmake --build build

    - name: Create Release Directory
      run: mkdir release

    - name: Move Library to Release
      run: move build\lib\Debug\UnitiGameEngine.lib release\

    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref }} # Utilisez la balise (tag) de la version actuelle
        files: release/* # Spécifiez les fichiers que vous voulez inclure dans la release
      env:
        GITHUB_TOKEN: "token_release"
