name: Lint C++ Code

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Set up Clang Format
        run: |
          sudo apt-get update -y
          sudo apt-get install -y clang-format
          clang-format --version

      - name: Lint C++ Code
        run: |
          find . -name "*.cpp" -exec clang-format -i -style=file {} \;

      - name: Get branch name
        id: extract_branch
        run: echo "##[set-output name=branch;]$(echo $GITHUB_REF | awk -F'/' '{print $3}')"

      - name: Commit Changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git fetch origin pull/${{ steps.extract_branch.outputs.branch }}/head:${{ steps.extract_branch.outputs.branch }}
          git checkout ${{ steps.extract_branch.outputs.branch }}
          git add .
          git diff --staged --quiet || git commit -m "Apply Clang Format"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
