name: Lint C++ Codes

on:
  workflow_run:
    workflows: ["buildlinux"]
    types:
      - completed

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Set up Clang Format
        run: |
          sudo apt-get update -y
          sudo apt-get install -y clang-format
          clang-format --version

      - name: Lint C++ Code
        run: |
          find . -name "*.cpp" -exec clang-format -i -style=file {} \;

      - name: Commit Changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git diff --staged --quiet || git commit -m "Apply Clang Format"

      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
