name: buildwindow

on:
  push:
    tags:
      - '*'
  pull_request: # Ajout de la vérification des PR
    branches:
      - '*'

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up CMake
        run: cmake -S . -B build

      - name: Build with CMake
        run: cmake --build build --config Release