jobs:
  build-windows:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
    - name: Set up MSVC environment
      uses: msys2/setup-msys2@v2
      with:
        arch: x86_64

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure and build
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
        cmake --build . --config Release
